name = "SshDataBridge"
uuid = "a37c1541-b844-4821-b3b3-8ec236b28b74"
authors = ["Paul-Adrian Gogîță <gogitapaul@yahoo.ro>"]
version = "0.2.0"
license = "MIT"

[deps]
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"

[compat]
Logging = "1"
TOML = "1"
julia = "1.10"
